
services:
  postgres:
    image: postgres:15.5
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/15/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mydb}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}

  # Redis (for cache & server session management)
  redis:
    image: redis:alpine
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-mypassword}
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - redis_data:/data


  # Chrome Browser (for printing and previews)
  chrome:
    image: browserless/chrome:1-chrome-stable
    restart: unless-stopped
    ports:
      - ${CHROME_PORT:-3004}:3004
    environment:
      KEEP_ALIVE: true
      CONNECTION_TIMEOUT: 10000
      EXIT_ON_HEALTH_FAILURE: true
      PRE_REQUEST_HEALTH_CHECK: true
      TOKEN: ${CHROME_TOKEN:-chrome_token}
      PORT: ${CHROME_PORT:-3004}

volumes:
  postgres:
  redis_data: