name: Deploy to Aliyun ECS

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      DOCKER_USER_PASSWORD: ${{secrets.DOCKER_USER_PASSWORD}}
      DOCKER_SERVER_IMAGE: ${{secrets.DOCKER_SERVER_IMAGE}}
      DOCKER_COMPOSE_PATH: ${{secrets.DOCKER_COMPOSE_PATH}}

      ECS_HOST: ${{ secrets.ECS_HOST }}
      ECS_USERNAME: ${{ secrets.ECS_USERNAME }}
      ECS_PASSWORD: ${{ secrets.ECS_PASSWORD }}

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 8.11.0
          run_install: false

      - name: Install dependencies and build
        run: pnpm install && pnpm run prisma:generate && pnpm run build

      - name: Apply all pending migrations to the database
        run: pnpm run prisma:deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3
        id: server
      - uses: docker/setup-buildx-action@v3
        id: board

      - name: Builder server name
        run: echo ${{ steps.server.outputs.name }}
      - name: Builder board name
        run: echo ${{ steps.board.outputs.name }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_USER_PASSWORD }}

      - name: Build against server
        uses: docker/build-push-action@v4
        with:
          builder: ${{ steps.server.outputs.name }}
          context: .
          target: server
          push: true
          platforms: linux/amd64
          tags: ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_SERVER_IMAGE}}:latest
      # - name: Build against builder2
      #   uses: docker/build-push-action@v5
      #   with:
      #     builder: ${{ steps.builder2.outputs.name }}
      #     context: .
      #     target: server

      # - name: Build and push image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     push: true
      #     platforms: linux/amd64
      #     tags: ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_SERVER_IMAGE}}:latest

      - name: Deploy to Aliyun ECS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ECS_HOST }}
          username: ${{ secrets.ECS_USERNAME }}
          password: ${{ secrets.ECS_PASSWORD }}
          script: |
            cd ${{secrets.DOCKER_COMPOSE_PATH}}
            docker compose -f docker-compose.yml pull
            docker compose -f docker-compose.yml up -d
