name: Deploy to Aliyun ECS

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      DOCKER_USER_PASSWORD: ${{secrets.DOCKER_USER_PASSWORD}}
      DOCKER_SERVER_IMAGE: ${{secrets.DOCKER_SERVER_IMAGE}}
      DOCKER_BOARD_IMAGE: ${{secrets.DOCKER_BOARD_IMAGE}}
      DOCKER_WEB_IMAGE: ${{secrets.DOCKER_WEB_IMAGE}}
      DOCKER_COMPOSE_PATH: ${{secrets.DOCKER_COMPOSE_PATH}}

      ECS_HOST: ${{ secrets.ECS_HOST }}
      ECS_USERNAME: ${{ secrets.ECS_USERNAME }}
      ECS_PASSWORD: ${{ secrets.ECS_PASSWORD }}

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: free disk space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h

      - name: Setup pnpm
        uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 8.11.0
          run_install: false

      - name: Install dependencies and build
        run: pnpm install && pnpm run prisma:generate && pnpm run build

      - name: Apply all pending migrations to production's database
        run: pnpm run prisma:deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3
        id: server
      - uses: docker/setup-buildx-action@v3
        id: board
      - uses: docker/setup-buildx-action@v3
        id: web

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_USER_PASSWORD }}

      - name: Build server application image
        uses: docker/build-push-action@v4
        with:
          builder: ${{ steps.server.outputs.name }}
          context: .
          target: server
          push: true
          platforms: linux/amd64
          tags: ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_SERVER_IMAGE}}:latest

      - name: Build board application image
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.board.outputs.name }}
          context: .
          target: board
          push: true
          platforms: linux/amd64
          tags: ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_BOARD_IMAGE}}:latest

      - name: Build web application image
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.web.outputs.name }}
          context: .
          target: web
          push: true
          platforms: linux/amd64
          tags: ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_WEB_IMAGE}}:latest

      - name: Deploy to Aliyun ECS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ECS_HOST }}
          username: ${{ secrets.ECS_USERNAME }}
          password: ${{ secrets.ECS_PASSWORD }}
          script: |
            cd ${{secrets.DOCKER_COMPOSE_PATH}}
            docker compose -f docker-compose.yml pull
            docker compose -f docker-compose.yml up -d
